{
 "title": "Telemetria",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 15, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"\n  height: 100%;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n\">\n\n  <div style=\"\n    display: flex;\n    align-items: center;\n    gap: 30px;\n  \">\n\n    <img\n      src=\"https://uniavan.edu.br/wp-content/uploads/2022/08/Logo-Uniavan-rodape-2048x723.png.webp\"\n      style=\"\n        width: 220px;\n        height: auto;\n      \"\n    >\n\n    <div style=\"\n      color: #ECEFF1;\n      font-family: Arial, sans-serif;\n      font-size: 34px;\n      font-weight: bold;\n      white-space: nowrap;\n    \">\n      Sistema de Monitoramento Elétrico de Motores\n    </div>\n\n  </div>\n\n</div>"
   }
  },
  {
   "title": "ESP32",
   "type": "stat",
   "description": "Indica se o ESP32 está online ou não. Se aparecer offline, provavelmente houve perda de comunicação ou o dispositivo está desligado.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoramento_motores\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"status_esp32\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"esp_online\")\r\n  |> filter(fn: (r) => r[\"dispositivo\"] == \"ESP32_TCC_UNIAVAN\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Wi-FI",
   "type": "gauge",
   "description": "Mostra a qualidade do sinal da rede.",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoramento_motores\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grandezas_eletricas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rssi\")\r\n  |> filter(fn: (r) => r[\"dispositivo\"] == \"ESP32_TCC_UNIAVAN\")\r\n  |> filter(fn: (r) => r[\"tipo_carga\"] == \"motor_eletrico\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "POTÊNCIA ATIVA",
   "type": "gauge",
   "description": "Visão rápida de quanto o motor está consumindo no momento.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoramento_motores\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grandezas_eletricas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"potencia_total\")\r\n  |> filter(fn: (r) => r[\"dispositivo\"] == \"ESP32_TCC_UNIAVAN\")\r\n  |> filter(fn: (r) => r[\"tipo_carga\"] == \"motor_eletrico\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "TENSÃO AO LONGO DO TEMPO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoramento_motores\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grandezas_eletricas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tensao_r\" or r[\"_field\"] == \"tensao_s\" or r[\"_field\"] == \"tensao_t\")\r\n  |> filter(fn: (r) => r[\"dispositivo\"] == \"ESP32_TCC_UNIAVAN\")\r\n  |> filter(fn: (r) => r[\"tipo_carga\"] == \"motor_eletrico\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "TENSÃO",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoramento_motores\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grandezas_eletricas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tensao_r\" or r[\"_field\"] == \"tensao_s\" or r[\"_field\"] == \"tensao_t\")\r\n  |> filter(fn: (r) => r[\"dispositivo\"] == \"ESP32_TCC_UNIAVAN\")\r\n  |> filter(fn: (r) => r[\"tipo_carga\"] == \"motor_eletrico\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CORRENTE AO LONGO DO TEMPO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoramento_motores\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grandezas_eletricas\")\r\n  |> filter(fn: (r) => contains(value: r[\"_field\"], set: [\"corrente_r\", \"corrente_s\", \"corrente_t\"]))\r\n  |> filter(fn: (r) => r[\"dispositivo\"] == \"ESP32_TCC_UNIAVAN\")\r\n  |> filter(fn: (r) => r[\"tipo_carga\"] == \"motor_eletrico\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CORRENTE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoramento_motores\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grandezas_eletricas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"corrente_r\" or r[\"_field\"] == \"corrente_s\" or r[\"_field\"] == \"corrente_t\")\r\n  |> filter(fn: (r) => r[\"dispositivo\"] == \"ESP32_TCC_UNIAVAN\")\r\n  |> filter(fn: (r) => r[\"tipo_carga\"] == \"motor_eletrico\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "POTÊNCIA AO LONGO DO TEMPO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoramento_motores\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grandezas_eletricas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"potencia_r\" or r[\"_field\"] == \"potencia_s\" or r[\"_field\"] == \"potencia_t\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "POTÊNCIA",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoramento_motores\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grandezas_eletricas\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"potencia_r\" or r[\"_field\"] == \"potencia_s\" or r[\"_field\"] == \"potencia_t\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}